### ISSUE TITLE
TODO´s

### ISSUE THREAD

**Issue by paulo-manzone** [BabiEste/mnc-sistemas-lineares#1]
Todo´s
##################################
- [x] Método de Gauss simples
- [x] Método de Gauss pivotamento parcial
- [ ] Método de Gauss pivotamento total
- [ ] Método de LU
- [ ] Método de Cholesky
- [ ] Cálculo do Determinante
- [ ] Cálculo da Inversa
- [ ] Método de Jacobi-Richardson
- [ ] Método de Gauss-Seidel
##################################
